// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`.

// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports

import 'dart:convert';
import 'dart:typed_data';

import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'dart:ffi' as ffi;

abstract class PingBridge {
  Future<void> runPing({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kRunPingConstMeta;

  Future<int> addOne({required int number, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAddOneConstMeta;
}

class PingBridgeImpl extends FlutterRustBridgeBase<PingBridgeWire>
    implements PingBridge {
  factory PingBridgeImpl(ffi.DynamicLibrary dylib) =>
      PingBridgeImpl.raw(PingBridgeWire(dylib));

  PingBridgeImpl.raw(PingBridgeWire inner) : super(inner);

  Future<void> runPing({dynamic hint}) => executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_run_ping(port_),
        parseSuccessData: _wire2api_unit,
        constMeta: kRunPingConstMeta,
        argValues: [],
        hint: hint,
      ));

  FlutterRustBridgeTaskConstMeta get kRunPingConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "run_ping",
        argNames: [],
      );

  Future<int> addOne({required int number, dynamic hint}) =>
      executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_add_one(port_, _api2wire_i32(number)),
        parseSuccessData: _wire2api_i32,
        constMeta: kAddOneConstMeta,
        argValues: [number],
        hint: hint,
      ));

  FlutterRustBridgeTaskConstMeta get kAddOneConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "add_one",
        argNames: ["number"],
      );

  // Section: api2wire
  int _api2wire_i32(int raw) {
    return raw;
  }

  // Section: api_fill_to_wire

}

// Section: wire2api
int _wire2api_i32(dynamic raw) {
  return raw as int;
}

void _wire2api_unit(dynamic raw) {
  return;
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.

/// generated by flutter_rust_bridge
class PingBridgeWire implements FlutterRustBridgeWireBase {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  PingBridgeWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  PingBridgeWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void wire_run_ping(
    int port_,
  ) {
    return _wire_run_ping(
      port_,
    );
  }

  late final _wire_run_pingPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_run_ping');
  late final _wire_run_ping =
      _wire_run_pingPtr.asFunction<void Function(int)>();

  void wire_add_one(
    int port_,
    int number,
  ) {
    return _wire_add_one(
      port_,
      number,
    );
  }

  late final _wire_add_onePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
          'wire_add_one');
  late final _wire_add_one =
      _wire_add_onePtr.asFunction<void Function(int, int)>();

  void free_WireSyncReturnStruct(
    WireSyncReturnStruct val,
  ) {
    return _free_WireSyncReturnStruct(
      val,
    );
  }

  late final _free_WireSyncReturnStructPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturnStruct)>>(
          'free_WireSyncReturnStruct');
  late final _free_WireSyncReturnStruct = _free_WireSyncReturnStructPtr
      .asFunction<void Function(WireSyncReturnStruct)>();

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;
typedef DartPort = ffi.Int64;
